DROP TABLE ANSWERS CASCADE CONSTRAINTS;

DROP TABLE HINTS CASCADE CONSTRAINTS;

DROP TABLE LIKES CASCADE CONSTRAINTS;

DROP TABLE QUESTION_ANSWER CASCADE CONSTRAINTS;

DROP TABLE QUESTIONS CASCADE CONSTRAINTS;

DROP TABLE RESULTS CASCADE CONSTRAINTS;

DROP TABLE TAGS CASCADE CONSTRAINTS;

DROP TABLE TEST_QUESTION CASCADE CONSTRAINTS;

DROP TABLE TEST_TAG CASCADE CONSTRAINTS;

DROP TABLE TESTS CASCADE CONSTRAINTS;

DROP TABLE TYPES CASCADE CONSTRAINTS;

DROP TABLE USERS CASCADE CONSTRAINTS;

DROP SEQUENCE ANSWERS_ANSWERID_SEQ;

DROP SEQUENCE HINTS_HINTID_SEQ;

DROP SEQUENCE LIKES_LIKEID_SEQ;

DROP SEQUENCE QUESTION_ANSWER_QAID_SEQ;

DROP SEQUENCE QUESTIONS_QUESTIONID_SEQ;

DROP SEQUENCE RESULTS_RESULTID_SEQ;

DROP SEQUENCE TAGS_TAGID_SEQ;

DROP SEQUENCE TEST_QUESTION_TQID_SEQ;

DROP SEQUENCE TESTS_TESTID_SEQ;

DROP SEQUENCE TYPES_TYPEID_SEQ;

DROP SEQUENCE USERS_USERID_SEQ;

COMMIT;