-- Generated by Oracle SQL Developer Data Modeler 24.3.0.240.1210
--   at:        2024-12-01 16:49:32 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE answers (
    answerid INTEGER NOT NULL
);

ALTER TABLE answers ADD CONSTRAINT answers_pk PRIMARY KEY ( answerid );

CREATE TABLE groups (
    groupid      INTEGER NOT NULL,
    name         VARCHAR2(20 CHAR) NOT NULL,
    users_userid INTEGER NOT NULL,
    tests_testid INTEGER NOT NULL
);

ALTER TABLE groups ADD CONSTRAINT groups_pk PRIMARY KEY ( groupid );

CREATE TABLE hints (
    hintid INTEGER NOT NULL,
    text   VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE hints ADD CONSTRAINT hints_pk PRIMARY KEY ( hintid );

CREATE TABLE question_answer (
    answers_answerid     INTEGER NOT NULL,
    questions_questionid INTEGER NOT NULL
);

ALTER TABLE question_answer ADD CONSTRAINT relation_15_pk PRIMARY KEY ( answers_answerid,
                                                                        questions_questionid );

CREATE TABLE questions (
    questionid   INTEGER NOT NULL,
    text         VARCHAR2(50 CHAR) NOT NULL,
    hints_hintid INTEGER,
    types_typeid INTEGER NOT NULL
);

ALTER TABLE questions ADD CONSTRAINT questions_pk PRIMARY KEY ( questionid );

CREATE TABLE results (
    resultid     INTEGER NOT NULL,
    points       INTEGER NOT NULL,
    "Date"       DATE NOT NULL,
    users_userid INTEGER NOT NULL,
    tests_testid INTEGER NOT NULL
);

ALTER TABLE results ADD CONSTRAINT results_pk PRIMARY KEY ( resultid );

CREATE TABLE tags (
    tagid INTEGER NOT NULL,
    name  VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE tags ADD CONSTRAINT tags_pk PRIMARY KEY ( tagid );

CREATE TABLE test_question (
    tests_testid         INTEGER NOT NULL,
    questions_questionid INTEGER NOT NULL
);

ALTER TABLE test_question ADD CONSTRAINT relation_9_pk PRIMARY KEY ( tests_testid,
                                                                     questions_questionid );

CREATE TABLE test_tag (
    tests_testid INTEGER NOT NULL,
    tags_tagid   INTEGER NOT NULL
);

ALTER TABLE test_tag ADD CONSTRAINT relation_10_pk PRIMARY KEY ( tests_testid,
                                                                 tags_tagid );

CREATE TABLE tests (
    testid INTEGER NOT NULL,
    name   VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE tests ADD CONSTRAINT tests_pk PRIMARY KEY ( testid );

CREATE TABLE types (
    typeid      INTEGER NOT NULL,
    description VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE types ADD CONSTRAINT types_pk PRIMARY KEY ( typeid );

CREATE TABLE users (
    userid   INTEGER NOT NULL,
    login    VARCHAR2(20 CHAR) NOT NULL,
    password VARCHAR2(64 BYTE) NOT NULL,
    email    VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY ( userid );

ALTER TABLE groups
    ADD CONSTRAINT groups_tests_fk FOREIGN KEY ( tests_testid )
        REFERENCES tests ( testid );

ALTER TABLE groups
    ADD CONSTRAINT groups_users_fk FOREIGN KEY ( users_userid )
        REFERENCES users ( userid );

ALTER TABLE questions
    ADD CONSTRAINT questions_hints_fk FOREIGN KEY ( hints_hintid )
        REFERENCES hints ( hintid );

ALTER TABLE questions
    ADD CONSTRAINT questions_types_fk FOREIGN KEY ( types_typeid )
        REFERENCES types ( typeid );

ALTER TABLE test_tag
    ADD CONSTRAINT relation_10_tags_fk FOREIGN KEY ( tags_tagid )
        REFERENCES tags ( tagid );

ALTER TABLE test_tag
    ADD CONSTRAINT relation_10_tests_fk FOREIGN KEY ( tests_testid )
        REFERENCES tests ( testid );

ALTER TABLE question_answer
    ADD CONSTRAINT relation_15_answers_fk FOREIGN KEY ( answers_answerid )
        REFERENCES answers ( answerid );

ALTER TABLE question_answer
    ADD CONSTRAINT relation_15_questions_fk FOREIGN KEY ( questions_questionid )
        REFERENCES questions ( questionid );

ALTER TABLE test_question
    ADD CONSTRAINT relation_9_questions_fk FOREIGN KEY ( questions_questionid )
        REFERENCES questions ( questionid );

ALTER TABLE test_question
    ADD CONSTRAINT relation_9_tests_fk FOREIGN KEY ( tests_testid )
        REFERENCES tests ( testid );

ALTER TABLE results
    ADD CONSTRAINT results_tests_fk FOREIGN KEY ( tests_testid )
        REFERENCES tests ( testid );

ALTER TABLE results
    ADD CONSTRAINT results_users_fk FOREIGN KEY ( users_userid )
        REFERENCES users ( userid );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             24
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
