-- Generated by Oracle SQL Developer Data Modeler 24.3.0.240.1210
--   at:        2025-01-14 20:58:12 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

create table answers (
   answerid             integer not null,
   text                 varchar2(80 char) not null,
   iscorrect            char(1) not null,
   image                blob,
   questions_questionid integer not null
);

alter table answers add constraint answers_pk primary key ( answerid );

create table hints (
   hintid integer not null,
   text   varchar2(50 char) not null
);

alter table hints add constraint hints_pk primary key ( hintid );

create table likes (
   likeid       integer not null,
   "Date"       date not null,
   users_userid integer not null,
   tests_testid integer not null
);

alter table likes add constraint likes_pk primary key ( likeid );

create table questions (
   questionid   integer not null,
   text         varchar2(50 char) not null,
   hints_hintid integer,
   types_typeid integer not null,
   image        blob,
   timelimit    integer,
   position     integer not null,
   tests_testid integer not null
);

alter table questions add constraint questions_pk primary key ( questionid );

create table results (
   resultid     integer not null,
   points       integer not null,
   "Date"       date not null,
   users_userid integer not null,
   tests_testid integer not null
);

alter table results add constraint results_pk primary key ( resultid );

create table tags (
   tagid integer not null,
   name  varchar2(20 char) not null
);

alter table tags add constraint tags_pk primary key ( tagid );

create table test_tag (
   tests_testid integer not null,
   tags_tagid   integer not null
);

alter table test_tag add constraint test_tag_pk primary key ( tests_testid,
                                                              tags_tagid );

create table tests (
   testid       integer not null,
   name         varchar2(20 char) not null,
   users_userid integer not null,
   icon         blob,
   attempts     integer,
   timelimit    integer,
   shuffled     boolean,
   creationdate date not null,
   field        varchar2(100 char) not null,
   description  varchar2(180 char) not null
);

alter table tests add constraint tests_pk primary key ( testid );

create table types (
   typeid      integer not null,
   description varchar2(50 char) not null
);

alter table types add constraint types_pk primary key ( typeid );

create table users (
   userid          integer not null,
   login           varchar2(20 char) not null,
   password        varchar2(64 byte) not null,
   email           varchar2(30 char) not null,
   icon            blob,
   isactive        char(1) default 'T' not null,
   visibilitylevel integer default 0 not null
);

alter table users add constraint users_pk primary key ( userid );

alter table answers
   add constraint answers_questions_fk foreign key ( questions_questionid )
      references questions ( questionid );

alter table likes
   add constraint likes_tests_fk foreign key ( tests_testid )
      references tests ( testid );

alter table likes
   add constraint likes_users_fk foreign key ( users_userid )
      references users ( userid );

alter table questions
   add constraint questions_hints_fk foreign key ( hints_hintid )
      references hints ( hintid );

alter table questions
   add constraint questions_tests_fk foreign key ( tests_testid )
      references tests ( testid );

alter table questions
   add constraint questions_types_fk foreign key ( types_typeid )
      references types ( typeid );

alter table results
   add constraint results_tests_fk foreign key ( tests_testid )
      references tests ( testid );

alter table results
   add constraint results_users_fk foreign key ( users_userid )
      references users ( userid );

alter table test_tag
   add constraint test_tag_tags_fk foreign key ( tags_tagid )
      references tags ( tagid );

alter table test_tag
   add constraint test_tag_tests_fk foreign key ( tests_testid )
      references tests ( testid );

alter table tests
   add constraint tests_users_fk foreign key ( users_userid )
      references users ( userid );

create sequence answers_answerid_seq start with 1 nocache order;

create or replace trigger answers_answerid_trg before
   insert on answers
   for each row
   when ( new.answerid is null )
begin
   :new.answerid := answers_answerid_seq.nextval;
end;
/

create sequence hints_hintid_seq start with 1 nocache order;

create or replace trigger hints_hintid_trg before
   insert on hints
   for each row
   when ( new.hintid is null )
begin
   :new.hintid := hints_hintid_seq.nextval;
end;
/

create sequence likes_likeid_seq start with 1 nocache order;

create or replace trigger likes_likeid_trg before
   insert on likes
   for each row
   when ( new.likeid is null )
begin
   :new.likeid := likes_likeid_seq.nextval;
end;
/

create sequence questions_questionid_seq start with 1 nocache order;

create or replace trigger questions_questionid_trg before
   insert on questions
   for each row
   when ( new.questionid is null )
begin
   :new.questionid := questions_questionid_seq.nextval;
end;
/

create sequence results_resultid_seq start with 1 nocache order;

create or replace trigger results_resultid_trg before
   insert on results
   for each row
   when ( new.resultid is null )
begin
   :new.resultid := results_resultid_seq.nextval;
end;
/

create sequence tags_tagid_seq start with 1 nocache order;

create or replace trigger tags_tagid_trg before
   insert on tags
   for each row
   when ( new.tagid is null )
begin
   :new.tagid := tags_tagid_seq.nextval;
end;
/

create sequence tests_testid_seq start with 1 nocache order;

create or replace trigger tests_testid_trg before
   insert on tests
   for each row
   when ( new.testid is null )
begin
   :new.testid := tests_testid_seq.nextval;
end;
/

create sequence types_typeid_seq start with 1 nocache order;

create or replace trigger types_typeid_trg before
   insert on types
   for each row
   when ( new.typeid is null )
begin
   :new.typeid := types_typeid_seq.nextval;
end;
/

create sequence users_userid_seq start with 1 nocache order;

create or replace trigger users_userid_trg before
   insert on users
   for each row
   when ( new.userid is null )
begin
   :new.userid := users_userid_seq.nextval;
end;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             21
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           9
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          9
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0